#!/usr/bin/env bash

PROFILE_NAME="full"
RUN_TIMEOUT_SECONDS="${RUN_TIMEOUT_SECONDS:-14400}"

FULL_TOTAL_TRAINING_STEPS="${FULL_TOTAL_TRAINING_STEPS:-50}"

PROFILE_OVERRIDES=(
  "trainer.total_training_steps=${FULL_TOTAL_TRAINING_STEPS}"
)
